# Projekt-Einstellungen für AGP 9.0+
android.useAndroidX=true
android.uniquePackageNames=true
android.enableAppCompileTimeRClass=true
android.r8.optimizedResourceShrinking=true
android.r8.strictFullModeForKeepRules=true
android.disallowKotlinSourceSets=false
org.gradle.jvmargs=-Xmx4g

# Diese Werte sind ab AGP 9.0 standardmäßig true, wir können sie also weglassen oder explizit setzen:
# android.builtInKotlin=true
# android.newDsl=true
